---
abstract: 'Prima application for displaying shader toys'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-ShaderToy
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  File::Basename: '0'
  File::Spec: '0'
  Filesys::Notify::Simple: '0'
  Filter::signatures: '0.06'
  OpenGL::Modern: '0.01'
  Prima: '1.49'
  Prima::OpenGL: '0.07'
  Thread::Queue: '0'
  Time::Slideshow: '0.01'
  perl: '5.006'
  threads: '0'
resources:
  repository: git://github.com/Corion/app-shadertoy.git
version: '0.01'
