=head1 NAME

OpenGL::Glew::FAQ

=head2 C<glXXX> not available on this machine

If you are certain that your machine should be able to do this, did you
create the proper OpenGL context before trying to call the function?

    my $err = OpenGL::Glew::glewInit();
    if( $err != GLEW_OK ) {
        die "Couldn't initialize Glew: ".glewGetErrorString($err);
    };
